### ISSUE TITLE
Invalid Markup W3C

### ISSUE THREAD

**Issue by Looshus** [rtCamp/rtsocial#38] opened 2015-03-06 21:14 UTC
Hello, I love how quick this plugin is to load, but it has littered my site with validation errors:

<a href="http://www.skyscaffolding.co.uk">Sky Scaffolding (Midlands) Limited</a>

Errors are:
Duplicate ID rts_media_nonce
& did not start a character reference. (& probably should have been escaped as &amp;amp;.) 

Please can we see this corrected, I see someone commented on this about a year ago.

Keep up the good work!

**Comment by pranali333** [comment] 2015-03-11 13:59
Hello Looshus,

This issue has been fixed and we have releases new version of rtSocial. Please update the latest version in your site.
Kindly check and let us know if it solved your issue or you are still facing any.

Thank you.

Regards,
Pranali

**Comment by Looshus** [comment] 2015-03-11 14:19
Pranali,

Thank you for looking into this.

The duplicate ID issue has been resolved, the outstanding issue is the unescaped ampersands in the button link URLs.  See validation report here:

http://validator.w3.org/check?uri=http%3A%2F%2Fwww.skyscaffolding.co.uk%2F&charset=%28detect+automatically%29&doctype=Inline&ss=1&group=0&user-agent=W3C_Validator%2F1.3+http%3A%2F%2Fvalidator.w3.org%2Fservices\

As you can see in the above URL, validator.w3.org uses '%26' instead of '&'.

Nearly there.

Regards,

Luke

**Comment by Mukulsingh27** [comment] 2022-03-02 11:20
@pooja-muchandikar 
This issue has been fixed, according to the above comments comments.

**Comment by Mukulsingh27** [comment] 2022-03-07 06:30
@pooja-muchandikar 
I'm unable to reproduce and didn't find any relatable PR for the fix also didn't see any error occurring.

**Comment by pavanpatil1** [comment] 2022-03-07 11:52
As per comments issue has been fixed and not able to reproduce the issue, Hence closing this issue.

**Closed by pavanpatil1** 2022-03-07 11:52 UTC
