### ISSUE TITLE
Issue with Facebook & Pinterest

### ISSUE THREAD

**Issue by ank1traj** [rtCamp/rtsocial#68] opened 2021-09-03 05:12 UTC
### Environment
**OS** - Windows
**Browser** - Chrome
**Architecture** - x64
**WordPress Version** - 5.8
**Tested with Single site**
**Site URL** - https://ankitraj.dev5.rt.gw/

| name  | About  | labels  | assignees|
|---|---|---|---|
|  🐛 Bug Report |  Share on Pinterest and Facebook is blocked 🤔. | bug  |   |

- [ ]  **Description** - On sharing using rtSocial on Pinterest, getting an error that **Sorry, we were unable to fetch the image.**

**Expected** - On sharing using rtSocial on Pinterest, it should get saved to the **board on the Pinterest**

**NOTE** - Expected screencast is taken from the [site](https://blog.ankit-raj-dev3.rt.gw/)

![Untitled_ Sep 3, 2021 7_52 AM](https://user-images.githubusercontent.com/32160084/131941863-6440102a-a82b-4953-98a1-8f9998f44533.gif)

**Actual** - On sharing on Pinterest, while adding it on the board it throws an error **Something went wrong Sorry, we were unable to fetch the image.**

![Untitled_ Sep 3, 2021 7_52 AM](https://user-images.githubusercontent.com/32160084/131941503-02bf029c-c9bb-4b87-a90f-9f42d69561d6.gif)

- [ ] **Description** - On sharing using rtSocial on Facebook, getting an error that **401 authorization required.**

**Expected** - On sharing using rtSocial on Facebook, it should get a share on Facebook.

**NOTE** - Expected screencast is taken from the [site](https://blog.ankit-raj-dev3.rt.gw/)

![Untitled_ Sep 3, 2021 7_52 AM](https://user-images.githubusercontent.com/32160084/131944847-2b661376-4553-40c0-9c2d-013164238b3b.gif)

**Actual** - On sharing on Facebook, it throws an error **401 authorization required.**

![Untitled_ Sep 3, 2021 7_52 AM](https://user-images.githubusercontent.com/32160084/131944652-785d4599-94fc-4a04-83e9-9782c04b0f44.gif)

**Comment by pooja-muchandikar** [comment] 2022-03-03 07:32
@ank1traj @devanshijoshi9 

Cross-checked the issue at my end and even I am facing the same issue as described in the issue description. 
 
<img width="1278" alt="Screenshot 2022-03-03 at 1 02 06 PM" src="https://user-images.githubusercontent.com/41000648/156517547-fddf0ff9-c227-4365-8af6-fe216b1e76da.png">

**Comment by devanshijoshi9** [comment] 2022-03-03 09:01
Hi @pooja-muchandikar @ank1traj 
It is working from my side.
https://www.awesomescreenshot.com/video/7694509?key=453b208db1b2ce9446dbed78a37cc52f

**Comment by pooja-muchandikar** [comment] 2022-03-03 09:14
@devanshijoshi9 

The board which you created on pinterest is private or public?

**Comment by devanshijoshi9** [comment] 2022-03-03 09:14
It is working with both private and public board

**Comment by pooja-muchandikar** [comment] 2022-03-03 09:16
Let's get on a quick huddle

**Comment by pooja-muchandikar** [comment] 2022-03-03 09:28
##UPDATE:

Discussed the issue over a call with @devanshijoshi9 and found out that, the issue is that if site has http auth enabled then unable to share posts/media. 

Tried on site where http auth is not enabled and was able to successfully fetch images/posts. 

@devanshijoshi9 will confirm the same on here end, and if issue is related to http auth then we can close this issue as this won't be valid issue. 

To share posts/media the site should be publicly accessible. 

cc: @ank1traj

**Comment by devanshijoshi9** [comment] 2022-03-03 10:12
I tried with both http auth enabled and http auth disabled site and it’s working fine when there is no auth enabled on the site.

cc: @pooja-muchandikar @ank1traj

**Comment by pooja-muchandikar** [comment] 2022-03-03 10:56
In that case this issue becomes Invalid, as sharing would work on publicly accessible sites, right @devanshijoshi9 ?

**Comment by devanshijoshi9** [comment] 2022-03-03 11:03
Yes @pooja-muchandikar, Me and @ank1traj Tested with http auth enable site ( ankit-raj.rt.gw ) and it's not working but in http auth disable site ( raj-ankit.rt.gw ) it is working perfectly.

**Comment by alvitazwar** [comment] 2022-05-11 11:25
The issue seems tobe fixed

**Closed** 2022-05-11 11:25 UTC
